### ISSUE TITLE
更新zstd & Nethunter

### ISSUE THREAD

**Issue by uwu-gl** [Fyg369/Kernel-Action#1]
闲的没事看了看您的编译脚本，有很多需要修改的地方，请按照我修改仓库中docs文件夹下的教程再试一次，您应该修改clang版本，并且停止使用Google gcc

**Comment by uwu-gl** [comment]
强烈推荐您照搬我的github action

**Comment by Fyg369** [comment]
> 强烈推荐您照搬我的github action

好的，这个脚本也是根据dabao1955大佬小小的修改而来

**Comment by Fyg369** [comment]
zdtd当时怎么升级我给忘了，好像是一个脚本然后我在乌班图下生成文件后加入到内核里编译的

https://github.com/Fyg369/mcd_kernel_oneplus_sdm845

https://github.com/Fyg369/android_kernel_oneplus6

![6](https://github.com/Fyg369/Kernel-Action/assets/142138034/6c900ffb-13b7-490f-9384-929b8f614a68)

**Comment by uwu-gl** [comment]
> zdtd当时怎么升级我给忘了，好像是一个脚本然后我在乌班图下生成文件后加入到内核里编译的
> 
> https://github.com/Fyg369/mcd_kernel_oneplus_sdm845
> 
> https://github.com/Fyg369/android_kernel_oneplus6
> 
> ![6](https://private-user-images.githubusercontent.com/142138034/333801858-6c900ffb-13b7-490f-9384-929b8f614a68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjcwNjcsIm5iZiI6MTcxNjcyNjc2NywicGF0aCI6Ii8xNDIxMzgwMzQvMzMzODAxODU4LTZjOTAwZmZiLTEzYjctNDkwZi05Mzg0LTkyOWI4ZjYxNGE2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMjMyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGYwZjMwZmY2YjM5Njk2YTRhNGUyNmFkNWY2ZWExMGI5NTYzM2RiZjNiMmVjYmUwNzI2Mzg0ZWQ0MTljY2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oVoJA4rhO_7jtPYP8vEgQcsrqXMQzU-fY1r6p4o-xPY)


截图里的commit是吗
另外，您有tg或者是qq吗？这样沟通起来太麻烦了

**Comment by uwu-gl** [comment]
您有qq/Telegram吗？这样排查问题太麻烦了

**Comment by uwu-gl** [comment]
你好，我在我的内核的以下分支中开始了zstd测试：
 - oos/11.0-zstd
您有时间/兴趣测试吗？

**Comment by uwu-gl** [comment]
如果您想测试，请刷入这个刷机包：
[点击下载](https://github.com/uwu-gl/android_kernel_github_workflow/releases/download/OxygenOS_test_202405311928_manual/boot.zip)

如果出了什么问题，例如黑屏开不了机之类的，请抓log给我。另外，如果开机了，请您帮忙看看能不能将您需要的zstd内核配置全部打开

**Comment by Fyg369** [comment]
经测试官方内核也有人脸解锁，快速双击锁频和双击亮屏，多试几次自动黑屏的BUG，第三方内核也会出现暗屏无法调节亮度和黑屏的BUG

![1](https://github.com/Fyg369/Kernel-Action/assets/142138034/5e5818ee-a1d0-45bb-a3b2-4048e804d1a6)

![2](https://github.com/Fyg369/Kernel-Action/assets/142138034/8e59d412-66a9-4dda-94f6-c403a2dc841a)

**Comment by Fyg369** [comment]
> 如果您想测试，请刷入这个刷机包： [点击下载](https://github.com/uwu-gl/android_kernel_github_workflow/releases/download/OxygenOS_test_202405311928_manual/boot.zip)
> 
> 如果出了什么问题，例如黑屏开不了机之类的，请抓log给我。另外，如果开机了，请您帮忙看看能不能将您需要的zstd内核配置全部打开

可以正常开机没问题，快速切换双击锁屏和亮屏也没问题了，很棒！！！就是不知道有没有把zstd设置为默认

**Comment by uwu-gl** [comment]
nethunter有什么集成的方法吗…？

**Comment by Fyg369** [comment]
> nethunter有什么集成的方法吗…？

         if [ ${{ inputs.nethunter }} = true ]; then
             echo "::group:: Initializing Kali nethunter"
             aria2c https://github.com/Fyj69/Kali-defconfig-checker/raw/master/check-kernel-config
             bash check-kernel-config ${{ inputs.config }} -w
             if [ ${{ inputs.nethunter-patch }} = true ]; then
                 aria2c https://github.com/tomxi1997/kali-nethunter_patches/raw/main/add-rtl88xxau-5.6.4.2-drivers.patch
                 git apply add-rtl88xxau-5.6.4.2-drivers.patch
                #aria2c https://github.com/tomxi1997/kali-nethunter_patches/raw/main/add-wifi-injection.patch
                #git apply add-wifi-injection.patch
                 aria2c https://github.com/tomxi1997/kali-nethunter_patches/raw/main/fix-ath9k-naming-conflict.patch
                 git apply fix-ath9k-naming-conflict.patch
                 if [ "$SUBLEVEL" -lt "19" ]; then
                     aria2c https://github.com/tomxi1997/kali-nethunter_patches/raw/main/add-wifi-injection-4.14.patch
                     git apply add-wifi-injection-4.14.patch
                 fi
             else
                  echo "skip patch"
             fi
             echo "::endgroup::"
         fi

![38](https://github.com/Fyg369/Kernel-Action/assets/142138034/ad61c424-018e-4048-8977-420c8c982597)

**Comment by Fyg369** [comment]
![36](https://github.com/Fyg369/Kernel-Action/assets/142138034/93e0ad3b-732b-4533-b2a7-d0eb5b77ebf1)

**Comment by uwu-gl** [comment]
ok，下个周搞吧
我的时间不是很充裕
如果你方便的话，可以fork仓库然后做更改，然后提交pull request就行，我会通过的

**Comment by Fyg369** [comment]
> ok，下个周搞吧 我的时间不是很充裕 如果你方便的话，可以fork仓库然后做更改，然后提交pull request就行，我会通过的

nethunter补丁是已经添加过了吗？我刚用Acton编译竟然跳过补丁编译成功了。。。

**Comment by uwu-gl** [comment]
没加啊。。。

**Comment by Fyg369** [comment]
> 没加啊。。。

那就奇怪了，明明已经开启了打补丁配置，但在编译的时候自动跳过了就很骚

**Comment by uwu-gl** [comment]
> > 如果您想测试，请刷入这个刷机包： [点击下载](https://github.com/uwu-gl/android_kernel_github_workflow/releases/download/OxygenOS_test_202405311928_manual/boot.zip)
> > 如果出了什么问题，例如黑屏开不了机之类的，请抓log给我。另外，如果开机了，请您帮忙看看能不能将您需要的zstd内核配置全部打开
> 
> 可以正常开机没问题，快速切换双击锁屏和亮屏也没问题了，很棒！！！就是不知道有没有把zstd设置为默认？要是能把内置ksu补丁去掉就好了，有时间看下能不能把nethunter补丁打进去，感谢您为一加6T官方11内核做贡献

你好，还在吗？
请教一下，
1.您对zstd如何使用？
2.是使用zram吗？[Y/n]
3.另外，您提到zstd不是默认，那么我是不是可以理解为您使用了某种手段开启了zstd？[Y/n]
3-1. 如果第3个问题回答是y，那么可以请教一下详细方式吗？
谢谢！

**Comment by Fyg369** [comment]
> > > 如果您想测试，请刷入这个刷机包： [点击下载](https://github.com/uwu-gl/android_kernel_github_workflow/releases/download/OxygenOS_test_202405311928_manual/boot.zip)
> > > 如果出了什么问题，例如黑屏开不了机之类的，请抓log给我。另外，如果开机了，请您帮忙看看能不能将您需要的zstd内核配置全部打开
> > 
> > 
> > 可以正常开机没问题，快速切换双击锁屏和亮屏也没问题了，很棒！！！就是不知道有没有把zstd设置为默认？要是能把内置ksu补丁去掉就好了，有时间看下能不能把nethunter补丁打进去，感谢您为一加6T官方11内核做贡献
> 
> 你好，还在吗？ 请教一下， 1.您对zstd如何使用？ 2.是使用zram吗？[Y/n] 3.另外，您提到zstd不是默认，那么我是不是可以理解为您使用了某种手段开启了zstd？[Y/n] 3-1. 如果第3个问题回答是y，那么可以请教一下详细方式吗？ 谢谢！

大佬源码里已经默认开启zstd，我只是升级了下zstd版本号

大佬一加6T源码：https://github.com/mcdachpappe/android_kernel_oneplus_sdm845
